SMSF/Presentation/SMSF.Web/Controllers/ImportsController.cs
using System.Globalization;
using DBASystem.SMSF.Contracts.Common;
using DBASystem.SMSF.Contracts.ViewModels;
using DBASystem.SMSF.Web.Common;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using Ionic.Zip;

namespace DBASystem.SMSF.Web.Controllers
{
    public class ImportsController : BaseController
    {
        public string GetTemplateXML(int id)
        {
            var requestXml = GenerateRequestXml(new GenericModel<int> { Value = id }, Option.GetTemplate);
            var responseModel = Execute(requestXml);
            var templates = (TemplateModel)ModelDeserializer.DeserializeFromXml<TemplateModel>(responseModel.ModelXml);
            return templates.TemplateText;
        }

        [OptionFilter(Option = Option.WorkPaper)]
        public ActionResult Index(string jobId)
        {
            jobId = Utility.DecryptQueryString(jobId);
            var requestXml = GenerateRequestXml(new GenericModel<int> { Value = Convert.ToInt32(jobId) }, Option.WorkPaper);
            var responseModel = Execute(requestXml);
            var model = (JobModel)ModelDeserializer.DeserializeFromXml<JobModel>(responseModel.ModelXml);
            return View(model);
        }

        public JsonResult GetTemplateProviders()
        {
            var templateProviders = new List<DictionaryModel<int, string>>();
            var requestXml = GenerateRequestXml(new GenericModel<int?>(), Option.GetTemplateProviders);
            var responseModel = Execute(requestXml);
            if (responseModel.Status == ResponseStatus.Success)
                templateProviders = ModelDeserializer.DeserializeListFromXml<DictionaryModel<int, string>>(responseModel.ModelXml);
            return Json(templateProviders, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTemplateCategories(string templateProviderId)
        {
            var templateCategories = new List<DictionaryModel<int, string>>();

            if (string.IsNullOrEmpty(templateProviderId))
                templateProviderId = "1";

            var requestXml = GenerateRequestXml(
                new GenericModel<int?> { Value = Convert.ToInt32(templateProviderId) }, Option.GetTemplateCategories);
            var responseModel = Execute(requestXml);
            if (responseModel.Status == ResponseStatus.Success)
                templateCategories =
                    ModelDeserializer.DeserializeListFromXml<DictionaryModel<int, string>>(responseModel.ModelXml);
            return Json(templateCategories, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTemplatesBy(string templateCategoryId)
        {
            var templates = new List<DictionaryModel<int, string>>();

            if (string.IsNullOrEmpty(templateCategoryId))
                templateCategoryId = "12";

            var requestXml = GenerateRequestXml(new GenericModel<int?> { Value = Convert.ToInt32(templateCategoryId) }, Option.GetTemplatesBy);
            var responseModel = Execute(requestXml);
            if (responseModel.Status == ResponseStatus.Success)
                templates = ModelDeserializer.DeserializeListFromXml<DictionaryModel<int, string>>(responseModel.ModelXml);
            return Json(templates, JsonRequestBehavior.AllowGet);
        }

        public string GetUploadedFileString(bool isPartial, JobsImportedDataModel jobsImportedDataModel,
            string templateXml, Stream fileBase)
        {
            string output;
            try
            {
                var template = templateXml;
                var engine = new Parser.Engine();
                engine.Load(fileBase, template);
                engine.Run();

                output = !engine.hasError
                    ? engine.output.ToString()
                    : string.Format("<b>Error in parsing= [{0}]</b>", engine.lastError);

                var httpPostedFileBase = Request.Files[0];
                if (httpPostedFileBase != null) ViewBag.FileName = httpPostedFileBase.FileName;
                SessionHelper.TemplateDataFileUploadStream = output;
            }
            catch (Exception e)
            {
                output = string.Format("<b>Error in parsing= [{0}]</b>", e.Message);
            }

            ViewBag.output = output;
            return ViewBag.output;
        }

        public JsonResult Parse(List<HttpPostedFileBase> fileUploader, int templateId, int jobId)
        {
            string output;
            var base64File = string.Empty;
            int templateTypeId = 0;
            try
            {
                if (jobId == 0) // single file
                {
                    base64File = Parsing(fileUploader, templateId);
                    output = ConvertXmlToJson(SessionHelper.TemplateDataFileUploadStream);
                }
                else // zip file
                {
                    string fileName = Path.GetFileName(fileUploader[0].FileName);
                    var guid = Guid.NewGuid();
                    var pathZip = Path.Combine(string.Format("{0}{1}_{2}", Server.MapPath("~/App_Data/"), guid, fileName));
                    string pathExtracted;
                    ///////////////////////////////////////////////////////////////
                    //1. Save in App_Data
                    ///////////////////////////////////////////////////////////////
                    fileUploader[0].SaveAs(pathZip);
                    ///////////////////////////////////////////////////////////////
                    //2. Extract
                    ///////////////////////////////////////////////////////////////
                    using (ZipFile zip = ZipFile.Read(pathZip))
                    {
                        pathExtracted = string.Format("{0}/{1}_ExtractFiles", Server.MapPath("~/App_Data"), guid);
                        zip.ExtractAll(pathExtracted, ExtractExistingFileAction.DoNotOverwrite);
                    }
                    ///////////////////////////////////////////////////////////////
                    //3. Iterate and Process Individual Files
                    ///////////////////////////////////////////////////////////////
                    var files = Directory.EnumerateFiles(pathExtracted);
                    var sb = new StringBuilder();

                    foreach (var file in files)
                    {
                        fileName = file.Substring(file.LastIndexOf("\\", StringComparison.Ordinal) + 1);

                        switch (fileName.Split('.')[1].ToString())
                        {
                            case "xls":
                                templateTypeId = GetBGLTemplateID(fileName, templateTypeId);
                                break;

                            case "pdf":
                                templateTypeId = GetDesktopSuperTemplateID(fileName.Split('.')[0].ToLower(), templateTypeId);
                                break;
                        }


                        if (templateTypeId == 0)
                        {
                            if (sb.Length == 0)
                            {
                                sb.AppendLine("Following file(s) have FAILED to import. <hr>");
                            }
                            sb.AppendLine(string.Format("<li> {0} </li>", fileName));
                            continue;
                        }
                        var templateXml = GetTemplateXML(templateTypeId);

                        var engine = new Parser.Engine();
                        engine.Load(templateXml, file);
                        engine.Run();

                        output = engine.output.ToString();
                        SessionHelper.TemplateDataFileUploadStream = output;

                        var fileStream = new FileStream(file, FileMode.Open, FileAccess.Read);
                        base64File = fileStream.ToBase64String();

                        Save(jobId.ToString(CultureInfo.InvariantCulture), templateTypeId.ToString(CultureInfo.InvariantCulture), fileName, base64File);
                        templateTypeId = 0;
                    }

                    if (sb.Length > 0)
                    {
                        sb.Insert(0, "<list>");
                        sb.AppendLine("</list><hr>");
                        sb.AppendLine("<b>Details:</b>  Either File Name(s) are incorrect Or Templates are not available for them.");
                    }

                    output = sb.ToString();
                    output = output == string.Empty ? "Zip file is successfully imported." : output;
                    ///////////////////////////////////////////////////////////////
                    //4. Delete Files
                    ///////////////////////////////////////////////////////////////
                    System.IO.File.Delete(pathZip);
                    Directory.Delete(pathExtracted, true);
                }
            }
            catch (Exception ex)
            {
                return
                    Json(
                        new
                        {
                            status = "error",
                            message = "Unable to parse the uploaded file.<br />" + ex.Message
                        }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { status = false, fileName = fileUploader[0].FileName, message = output, Base64File = base64File }, JsonRequestBehavior.AllowGet);
        }

        private int GetDesktopSuperTemplateID(string fileName, int templateTypeId)
        {
            if (fileName.Contains("cash flow") || fileName.Contains("cashflow") || fileName.Contains("cashflows") ||
                fileName.Contains("statement of cashflows"))
                templateTypeId = (int) ImportTemplate.DSStatementOfCashflows;

SMSF/Presentation/SMSF.Web/Views/Job/Index.cshtml
@{
    Layout = "~/Views/Shared/_WindowsAzureResponsiveNav.cshtml";
    ViewBag.Title = "Jobs";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
}

<style>
    .newtable {
        height: 100% !important;
    }
</style>

<nav id="secondary">
    @Html.Partial(Url.Content("~/Views/Firm/_SearchFilter.cshtml"))
</nav>
<div id="contentmain">
    <div id="contentinner">
        <h2>Jobs</h2>
        @Html.Partial(Url.Content("~/Views/Job/_Index.cshtml"))
    </div>
</div>
<div id="dvLoader" style="text-align: center; padding-top: 160px">
    <h4>Loading Jobs</h4><img src='@Url.Content("~/images/loadingdots.gif")' />
</div>

<script>
    var AlphaFilterList;
    $(function () {
         
        var optionValues =  jQuery.parseJSON('@Html.Raw(ViewBag.StatusList)');
        SetFirmGrid(null);
        var obj = [
            { 'Display': 'Status', 'Field': 'Status', 'selectedValue': '@ViewBag.StatusID', 'DefaultValue': optionValues , 'Type': 'ddl' },
            { 'Display': 'Firm', 'Field': 'Firm', 'DefaultValue': '@ViewBag.Firm', 'Type': 'txt', 'placeholder': 'Firm Name' },
            { 'Display': 'Account', 'Field': 'Account', 'DefaultValue': '@ViewBag.Account', 'Type': 'txt', 'placeholder': 'Accounts' },
            { 'Display': 'Fund', 'Field': 'Fund', 'DefaultValue': '', 'Type': 'txt', 'placeholder': 'Fund' },
            { 'Display': 'ABN', 'Field': 'ABN', 'DefaultValue': '@ViewBag.ABN', 'Type': 'txt', 'placeholder': 'Australian Business Number' },
            { 'Display': 'Account Manager', 'Field': 'AccountManager', 'DefaultValue': '@ViewBag.AccountManager', 'Type': 'txt', 'placeholder': 'Account Manager' },
            { 'Display': 'Primary Contact', 'Field': 'PrimaryContact', 'DefaultValue': '@ViewBag.PrimaryContact', 'Type': 'txt', 'placeholder': 'Primary Contact' },
            { 'Display': 'Date From', 'Field': 'CreationDate', 'DefaultValue': '@ViewBag.DateFrom', 'Type': 'date>', 'placeholder': 'Creation date from' },
            { 'Display': 'To', 'Field': 'CreationDate', 'DefaultValue': '@ViewBag.DateTo', 'Type': 'date<', 'placeholder': 'Creation date to' }
        ];
        setSearchFilter(obj);
        getSearchFilterModel();
    });
</script>

SMSF/Presentation/SMSF.Web/Views/Job/Overdue.cshtml
@{
    ViewBag.Title = "Overdue Jobs";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
}

<style>
    .newtable {
        height: 100% !important;
    }
</style>

<div id="contentmain">
    <div id="contentinner">
        <h2>Overdue Jobs</h2>
        @Html.Partial(Url.Content("~/Views/Job/_Overdue.cshtml"))
    </div>
</div>
<div id="dvLoader" style="text-align: center; padding-top: 160px">
    <h4>Loading Jobs</h4><img src='@Url.Content("~/images/loadingdots.gif")' />
</div>

<script>
    var AlphaFilterList;
    $(function () {
        
        SetFirmGrid(null);

        $.ajax({

            url: '/Job/IndexSearch',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({Status: -1}),
            type: "POST",
            cache: false,
            error: function (error) {
                window.location.href = '/Error/Index';
            },
            success: function (data) {
                dataModel = $.grep(data.data, function (d) {
                    return d.CategoryID != '1';
                });

                
                SetFirmGrid(dataModel);
                farmModel = dataModel;
                displaySearchAplha(dataModel);

                if (data.message != '') {

                    $('<div />', { id: 'dvMessage' }).html('Displaying 1,000 of ' + formatNumber(data.message) + ' records.').appendTo('body');

                    $('#dvMessage').fadeIn('slow');
                    $('#dvMessage').delay(5000).fadeOut('slow');
                }
            }
        });

    });
</script>

SMSF/Presentation/SMSF.Web/Views/Job/UpdateWorkPaper.cshtml
@using DBASystem.SMSF.Web.Common
@using DBASystem.SMSF.Contracts.Common
@using Kendo.Mvc.UI

@{
    ViewBag.Title = "Work Paper";
}
<style scoped>
    #lstManagers {
        padding: 10px;
        margin-bottom: -1px;
        width: 100%;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
}

<script src='@Url.Content("~/Scripts/jquery.tmpl.min.js")'></script>
<style>
    .newtable {
        height: 100% !important;
    }
</style>

<div id="contentmain">
    <div id="contentinner">
        <h2>Work Paper  <img src="/images/add.png" class="add" id="btnAddWorkpaper" title="Click to add WorkPaper"> </h2>
        <div id="toolbar">
            <div id="actionButtons">
                <button type="submit" class="btn btn-purple" id="btnBack">
                    <span class="icon-circle-arrow-left icon-white"></span> Back
                </button>

            </div>
            <div id="dvloader" style="display:none">
                <img src="~/Images/loader1.gif" />&nbsp;&nbsp;<span id="loaderMessage" style="color:white"></span>
            </div>
        </div>
        <script id="accountManagersTemplate" type="text/x-jquery-tmpl">
            <tr class="item">

                <td>
                    ${Caption}
                </td>
                <td style="text-align:right">
                    ${TabOrder}
                </td>
                <td style="text-align:center">
                    {{if IsViewable}} <input type="checkbox" value="${IsViewable}" checked="checked" disabled="disabled" />
                    {{else}} <input type="checkbox" value="${IsViewable}" disabled="disabled" />
                    {{/if}}
                </td>
                <td style="text-align:center">
                    <img id="${Id}" class="edit edituser" data-caption="${Caption}" data-id="${Id}" data-order="${TabOrder}" data-viewable="${IsViewable}" src="/Images/edit.png" onclick="editWorkPaper(this)" title="Click to edit this">
                    <img src='@Url.Content("~/images/delete.png")' class="deleteManager" data-id="${Id}" data-caption="${Caption}" data-order="${TabOrder}" data-viewable="${IsViewable}" title="Click to remove" onclick="deleteWorkPaper(this)" style="padding-left:5px" />
                </td>
            </tr>
        </script>
        
            <div id="divworkpaper"  style="display: none">
                
            </div>

        <div id="dvAccountManagers"  >
            <table class="table">
                <tr>
                    <th>Caption</th>
                    <th style="text-align:center" width="6%">Tab Order </th>
                    <th style="text-align:center" width="10%">Available for Clients </th>
                    <th style="width:8%; text-align:center "> </th>
                </tr>
                <tbody id="tablebody"></tbody>
            </table>
        </div>
    </div>
</div>
<div id="dvLoader" style="text-align: center; padding-top: 160px">
    <h4>Loading WorkPaper</h4><img src='@Url.Content("~/images/loadingdots.gif")' />
</div>


<script>
    $('#btnBack').click(back);
    function back() {
        window.location.href = '@Url.Action("SystemSettings", "Setting")';
    }

    $('#btnAddWorkpaper').click(function () {
        $('#txtorder').val('');
        $('#txtdescription').val('');
        $('#txtdescription').data('id', '');
        $('#btnSave').attr('value', 'Save');
        var title = 'Add WorkPaper';
        $('#divworkpaper').show();
        $('#addtable').remove();
        $('.divscr').remove();
        $('#divworkpaper').append("<table class='table' id='addtable'><tr><td><input id='txtdescription' type='text' placeholder='Description' /></td><td><input id='txtorder' type='number' class='form-control bfh-number' /></td><td style='text-align:center'><input id='chkavailable' type='checkbox' /></td><td><input id='btnSave' onclick='Save()' type='button' value='Save' /><input id='btnCancel' Style='margin-left:5px' onclick='reset()' type='button' value='Cancel' /></td></tr></table>");
        $('#btnSave').attr('value', 'Save');

    });

    function Save() {
        if ($('#txtdescription').val() == '') {
            doAlert('The field Description is required');
            return;
        }
        if ($('#txtorder').val() < 1) {
            doAlert('The required numberic only');
            return;
        }
        
        var workPaper = { "Id": $('#txtdescription').data('id'), "Caption": $('#txtdescription').val(), "TabOrder": $('#txtorder').val(), "EntityId": '@ViewBag.AccountId', "WorkpaperContentType": "", "ContentType": "1", "IsActive": true, "IsViewable": $('#chkavailable').prop('checked') };

        if ($('#btnSave').val() == 'Update') {

            $.ajax({
                url: '@Url.Content("~/AuditProcedure/UpdateAuditProcedureTab")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(workPaper),
                type: "POST",
                cache: false,
                error: function (error) {
                    window.location.href = '@Url.Content("~/Error/Index")';
                },
                success: function (data) {
                    bindData();
                }
            });
        } else {
            $.ajax({
                url: '@Url.Content("~/AuditProcedure/AddAuditProcedureTab")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(workPaper),
                type: "POST",
                cache: false,
                error: function (error) {
                    window.location.href = '@Url.Content("~/Error/Index")';
                },
                success: function (data) {
                    bindData();
                }
            });


        }
        reset();

    };
    function editWorkPaper(e) {
        $('#addtable').remove();
        var id = $(e).data('id');
        var desc = $(e).data('caption');
        var order = $(e).data('order');
        var isviewable = $(e).data('viewable');
        var title = 'Add WorkPaper';
        $('.divscr').remove();
        var td = $('<td>').append($('#divworkpaper').html());
        var tr = $('<tr class=divscr/>').append("<td><input id='txtdescription' type='text' placeholder='Description' /></td>").append("<td><input id='txtorder' type='number' class='form-control bfh-number' /></td>").append("<td style='text-align:center'><input id='chkavailable' type='checkbox' /></td>").append("<td><input id='btnSave' onclick='Save()' type='button' value='Save' /><input id='btnCancel' onclick='reset()' Style='margin-left:5px' type='button' value='Cancel' /></td>");
        $(e).parents("tr.item").after(tr);

        if (id != '') {
            $('#txtorder').val(order);
            $('#txtdescription').val(desc);
            $('#txtdescription').data('id', id);
            $('#chkavailable').prop('checked', isviewable);
            $('#btnSave').attr('value', 'Update');
        }
    }
    function reset() {
        $('.divscr').remove();
        $('#addtable').remove();
        $('#txtorder').val('');
        $('#txtdescription').val('');
        $('#txtdescription').data('id', '');
        $('#btnSave').attr('value', 'Save');
        $('#divworkpaper').dialog('close');
    }
    function Delete(id) {
        var item = { "AuditProcTabId": id, "JobId": 0, "AccountId": '@ViewBag.AccountId' };

        $.ajax({
            url: '@Url.Content("~/AuditProcedure/DeleteAuditProcedureTab")',
            type: "GET",
            data: item,
            cache: false,
            success: function (data) {
                bindData();
            }
        });
    }

    function deleteWorkPaper(e) {
        $('#addtable').remove();

        doConfirm('Are you sure want to remove this WorkPaper?',
               function yes() {
                   var id = $(e).data('id');
                   Delete(id);
               },
               function no() {
                   $(".item").css("background-color", "#fff");

               }
           );
    }

    function bindData() {
        var tdata = [];
        var item = { "AuditProcTabId": 0, "JobId": 0, "AccountId": '@ViewBag.AccountId' };
        
        $.ajax({
            url: '@Url.Content("~/AuditProcedure/GetAuditProcedureTabs")',
            type: "GET",
            data: item,
            cache: false,
            success: function (data) {
                bindManagersList(data);
                tdata = data;
            }

        });
        return tdata;
    }

    $(function () {
        $('#btnSave').text('Save');
        bindData();

    });

    function getParameterByName(name) {
        name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
        var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
            results = regex.exec(location.search);
        return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
    }
    function bindManagersList(selectedManagers) {
        var length = Object.keys(selectedManagers).length;

        var data = JSON.stringify(selectedManagers);
        var temp = $('#accountManagersTemplate').tmpl(selectedManagers);
        $('#tablebody').empty().html(temp);

        $(".item").click(function () {
            $(".item").css("background-color", "#fff");
            $(this).css("background-color", "#cdcdcd");
        });


    }
</script>

SMSF/Presentation/SMSF.Web/Views/Job/_JobMainMenu.cshtml
@using DBASystem.SMSF.Contracts.Common
@using DBASystem.SMSF.Contracts.ViewModels
@using DBASystem.SMSF.Web.Common
@*@model DBASystem.SMSF.Contracts.ViewModels.JobMainMenuViewModel*@
@{
    var jobId = ViewData["JobId"];
    var workpaperMenu = ViewData["WorkpaperMenu"] as bool?;
}


<div id="dvMainContainer">
    <div id="JobMainMenu">
        @if (jobId != null)
        {
            
            <ul id="JobMainMenuList">
                @if (CommonFunction.IsOptionAllowed(Option.GetJobInfo))
                {
                    <li><a href="@Url.Action("Detail", "Job", new {id = jobId})">General</a></li>
                }
                @if (CommonFunction.IsOptionAllowed(Option.GetImportTemplates))
                {
                    <li><a href="@Url.Action("Index", "Imports", new {jobId = jobId})">Imports</a></li>
                }
                @if (CommonFunction.IsOptionAllowed(Option.WorkPaper))
                {
                    <li><a href="@Url.Action("WorkPaper", "Job", new {jobId = jobId})">Work Papers</a></li>
                }
                @if (CommonFunction.IsOptionAllowed(Option.AuditReports))
                {
                    <li><a href="@Url.Action("AuditReports", "Job", new {jobId = jobId})">Audit Reports</a></li>
                }
                @if (CommonFunction.IsOptionAllowed(Option.GetWorkpaperMenu))
                {
                    <li>
                        <ul id="WorkPaperTabs">
                            @if (workpaperMenu.HasValue && workpaperMenu.Value == true)
                            {
                                var model = new ManageWorkPaperModel {JobId = Convert.ToInt32(Utility.DecryptQueryString(jobId.ToString()))};
                                Html.RenderAction("GetWorkpaperMenu", model);
                            }
                        </ul>
                    </li>
                }
                @if (CommonFunction.IsOptionAllowed(Option.GetWorkLogs))
                {
                    <li><a href="@Url.Action("WorkLog", "Job", new {jobId = jobId})">Work Log</a></li>
                }
                <li><a href="@Url.Action("Comments", "Job", new { id = jobId })">Comments</a></li>
            </ul>
        }
    </div>
</div>

SMSF/Presentation/SMSF.Web/Views/Job/_Overdue.cshtml
@using DBASystem.SMSF.Contracts.Common;

@Html.Partial(Url.Content("~/Views/Job/_List.cshtml"))

SMSF/Presentation/SMSF.Web/Views/Job/_WorkpaperMenu.cshtml
@foreach (var workPapers in Model.WorkPapers)
{
    <li>
        <a id="@workPapers.Id" href="#" class="content-workpaper" >@workPapers.Caption </a>
        <a href="/Job/UpdateWorkPaperContent?accountId=@ViewBag.AccountId&tabId=@workPapers.Id" style="display:inline-block;">
            <i class="fa fa-edit manage-show" id="@workPapers.Id" style="margin-left: 4px; display:none"></i>
        </a>

    </li>
}