SMSF/Presentation/SMSF.Web/Controllers/SettingController.cs
using DBASystem.SMSF.Contracts.Common;
using DBASystem.SMSF.Contracts.ViewModels;
using DBASystem.SMSF.Web.Common;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace DBASystem.SMSF.Web.Controllers
{
    public class SettingController : BaseController
    {
        public ActionResult Index(string Id)
        {
            ViewBag.IsPrimaryAccountManager = GetUserProfile(SessionHelper.UserId).IsPrimaryAccountManager;
            SessionHelper.SelectedMenu = "Settings";

            return View();
        }

        public ActionResult UserProfile()
        {
            ViewBag.IsPrimaryAccountManager = GetUserProfile(SessionHelper.UserId).IsPrimaryAccountManager;
            ViewBag.InitialTab = SettingHeads.UserProfile.ToString();
            SessionHelper.SelectedMenu = "Settings";
            return View("Index");
        }

        public ActionResult SystemSettings()
        {
            ViewBag.InitialTab = (SessionHelper.Group == UserGroup.Clients || SessionHelper.Group == UserGroup.Operators)
                ? SettingHeads.UserProfile.ToString()
                : SettingHeads.System.ToString();

            ViewBag.IsPrimaryAccountManager = GetUserProfile(SessionHelper.UserId).IsPrimaryAccountManager;
            SessionHelper.SelectedMenu = "Settings";
            return View("Index");
        }

        public ActionResult UserGroups()
        {
            return View();
        }

        public void GetAccounts()
        {
            var searchModel = new SearchFilterModel { UserID = SessionHelper.UserId, EntityType = EntityTypes.Client };
            var requestXml = GenerateRequestXml(searchModel, Option.GetAccounts);
            var responseModel = Execute(requestXml);
            var model = ModelDeserializer.DeserializeListFromXml<FirmModels>(responseModel.ModelXml);

            ViewBag.ClientAccounts = new SelectList(model, "ID", "Name");
        }

        public ActionResult GetSettings(SettingHeads settingHead)
        {
            var requestXml = "";
            ResponseModel responseModel;
            GetAccounts();
            switch (settingHead)
            {
                case SettingHeads.System:

                    requestXml = GenerateRequestXml(new GenericModel<SettingHeads> { Value = settingHead }, Option.GetSetting);
                    responseModel = Execute(requestXml);
                    if (responseModel.Status == ResponseStatus.Success)
                    {
                        var systemSettings = (SystemSettingsModel)ModelDeserializer.DeserializeFromXml<SystemSettingsModel>(responseModel.ModelXml);
                        return PartialView("_SystemSettings", systemSettings);
                    }
                    break;

                case SettingHeads.Sharepoint:

                    requestXml = GenerateRequestXml(new GenericModel<SettingHeads> { Value = settingHead }, Option.GetSetting);
                    responseModel = Execute(requestXml);
                    if (responseModel.Status == ResponseStatus.Success)
                    {
                        var sharepointSettings = (SharePointSettingModel)ModelDeserializer.DeserializeFromXml<SharePointSettingModel>(responseModel.ModelXml);
                        return PartialView("_SharepointSetting", sharepointSettings);
                    }
                    break;

                case SettingHeads.UserProfile:

                    var model = GetUserProfile(SessionHelper.UserId);
                    if (model.IsPrimaryAccountManager)
                        SessionHelper.ListAddresses = model.ListAddress;

                    SessionHelper.ListContacts = model.ListContact;

                    model.PasswordPolicy.ValidationExpression = "/" + model.PasswordPolicy.ValidationExpression + "/";
                    model.ListAddress = null;
                    return PartialView("_UserProfile", model);

                case SettingHeads.Enittes:
                    var objModel = GetUserProfile(SessionHelper.UserId);
                    if (objModel.IsPrimaryAccountManager)
                        SessionHelper.ListAddresses = objModel.ListAddress;

                    objModel.ListAddress = null;
                    return PartialView("_EntitySettings");

                case SettingHeads.Logs:
                    return PartialView("_Logs");

                case SettingHeads.DefaultDocuments:
                    requestXml = GenerateRequestXml(new GenericModel<SettingHeads> { Value = SettingHeads.Sharepoint }, Option.GetSetting);
                    responseModel = Execute(requestXml);
                    if (responseModel.Status == ResponseStatus.Success)
                    {
                        var sharepointSettings = (SharePointSettingModel)ModelDeserializer.DeserializeFromXml<SharePointSettingModel>(responseModel.ModelXml);
                        ViewBag.JobDefaultDocumentPath = sharepointSettings.JobDefaultDocumentsPath;
                    }

                    return PartialView("_DefaultDocuments");

                case SettingHeads.ReportsTemplates:
                    requestXml = GenerateRequestXml(new GenericModel<SettingHeads> { Value = SettingHeads.Sharepoint }, Option.GetSetting);
                    responseModel = Execute(requestXml);
                    if (responseModel.Status == ResponseStatus.Success)
                    {
                        var sharepointSettings = (SharePointSettingModel)ModelDeserializer.DeserializeFromXml<SharePointSettingModel>(responseModel.ModelXml);
                        ViewBag.ReportTemplatePath = sharepointSettings.ReportTemplatePath;
                    }

                    return PartialView("_FinalReportTemplates");
                case SettingHeads.ReportServer:
                    requestXml = GenerateRequestXml(new GenericModel<SettingHeads> { Value = settingHead }, Option.GetSetting);
                    responseModel = Execute(requestXml);
                    if (responseModel.Status == ResponseStatus.Success)
                    {
                        var reportServerModel = (ReportServerSettingModel)ModelDeserializer.DeserializeFromXml<ReportServerSettingModel>(responseModel.ModelXml);
                        return PartialView("_ReportServer", reportServerModel);
                    }
                    break;

                case SettingHeads.Groups:
                    requestXml = base.GenerateRequestXml(null, Option.GetUserGroups);
                    responseModel = base.Execute(requestXml);
                    var groups = (List<UserGroupModel>)ModelDeserializer.DeserializeListFromXml<UserGroupModel>(responseModel.ModelXml);
                    return PartialView("_UserGroups", groups);

                case SettingHeads.Roles:
                    return PartialView("_UserRolesList", GetRoles());
            }

            return View("Index");
        }

        [HttpPost]
        [OptionFilter(Option = Option.UpdateEmailSettings)]
        public ActionResult UpdateEmailSettings(EmailSettingsModel model)
        {
            model.ModifiedBy = SessionHelper.UserId;
            var requestXml = GenerateRequestXml(new GenericModel<EmailSettingsModel> { Value = model }, Option.UpdateEmailSettings);
            var responseModel = Execute(requestXml);

            return Json(new { success = responseModel.Status == ResponseStatus.Success });
        }

        [HttpPost]
        [OptionFilter(Option = Option.UpdatePasswordSettings)]
        public ActionResult UpdatePasswordSettings(PasswordSettingsModel model)
        {
            model.ModifiedBy = SessionHelper.UserId;
            var requestXml = GenerateRequestXml(new GenericModel<PasswordSettingsModel> { Value = model }, Option.UpdatePasswordSettings);
            var responseModel = Execute(requestXml);

            return Json(new { success = responseModel.Status == ResponseStatus.Success });
        }

        [HttpPost]
        [OptionFilter(Option = Option.UpdateSessionSettings)]
        public ActionResult UpdateSessionSettings(SessionSettingModel model)
        {
            model.ModifiedBy = SessionHelper.UserId;
            var requestXml = GenerateRequestXml(new GenericModel<SessionSettingModel> { Value = model }, Option.UpdateSessionSettings);
            var responseModel = Execute(requestXml);

            return Json(new { success = responseModel.Status == ResponseStatus.Success });
        }

        [HttpPost]
        [OptionFilter(Option = Option.UpdateSharepointSetting)]
        public ActionResult UpdateSharePointSetting(SharePointSettingModel model)
        {
            if (ModelState.IsValid)
            {
                model.ModifiedBy = SessionHelper.UserId;
                var requestXml = GenerateRequestXml(new GenericModel<SharePointSettingModel> { Value = model }, Option.UpdateSharepointSetting);
                var responseModel = Execute(requestXml);
                if (responseModel.Status == ResponseStatus.Success)
                {
                    SessionHelper.MaxUploadFileSize = model.MaximumFileSize;
                    SessionHelper.AllowedFileExtensions = model.AllowedFileTypeList;
                }
                return Json(new { success = responseModel.Status == ResponseStatus.Success });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        [OptionFilter(Option = Option.UpdateVersionSettings)]
        public ActionResult UpdateVersionSettings(VersionSettingModel model)
         {
            model.ModifiedBy = SessionHelper.UserId;
            model.ModifiedOn = DateTime.Now;

            var requestXml = GenerateRequestXml(new GenericModel<VersionSettingModel> { Value = model }, Option.UpdateVersionSettings);
            var responseModel = Execute(requestXml);
            if (responseModel.Status == ResponseStatus.Success)
            {

SMSF/Presentation/SMSF.Web/Views/Setting/Index.cshtml
@using DBASystem.SMSF.Web.Common
@using DBASystem.SMSF.Contracts.Common

@using Kendo.Mvc.UI

@{
    ViewBag.Title = "Settings";
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
}

<div id="contentmain">
    <div id="contentinner">

        <h2>Settings</h2>

        <div id="tabstrip">
            <ul>
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.System">System Settings</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.ReportServer">Report Server Settings</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.Sharepoint">Sharepoint Settings</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.Groups">User Groups</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.Roles">User Roles</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.DefaultDocuments">Job Default Documents</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.ReportsTemplates">Audit Report Template</li>
                }
                <li type="@SettingHeads.UserProfile">User Profile</li>
                @if (@ViewBag.IsPrimaryAccountManager)
                {
                    <li type="@SettingHeads.Enittes">Entity Settings</li>
                }
                @if (SessionHelper.Group == UserGroup.Administrators)
                {
                    <li type="@SettingHeads.Logs">Logs</li>
                }
            </ul>
            <div><div id="systemSettings"></div></div>
            <div><div id="reportServer"></div></div>
            <div><div id="sharepointSettings"></div></div>
            <div><div id="userGroupSettings"></div></div>
            <div><div id="userRoleSettings"></div></div>
            <div><div id="defaultDocuments"></div></div>
            <div><div id="reportsTemplates"></div></div>
            <div><div id="profile"></div></div>
            <div><div id="entitySettings"></div></div>
            <div><div id="logs"></div></div>
        </div>
        <div id="toolbar">
            <button id="btnUpdate" type="submit" class="btn btn-purple" style="display:none">
                <span class="fa fa-save"></span>Update
            </button>
            <div id="dvloader" style="display:none">
                <img src="~/Images/loader1.gif" />&nbsp;&nbsp;<span id="updateMessage"></span>
            </div>
        </div>
    </div>
</div>

<script>
    var loadedTabs = [];
    var formValuesChanged = false;
    $(function () {

        var tabstrip = $("#tabstrip").kendoTabStrip().data("kendoTabStrip");
        tabstrip.bind("select", onSelect);

        if ('@ViewBag.InitialTab' != '') {

            var index;
            switch ('@ViewBag.InitialTab') {
                case '@SettingHeads.UserProfile':
                    index = GetTabIndex('UserProfile', tabstrip.tabGroup[0].childNodes);
                    if (index != -1)
                        tabstrip.select(index);
                    break;
                case '@SettingHeads.System':
                    index = GetTabIndex('System', tabstrip.tabGroup[0].childNodes);
                    if (index != -1)
                        tabstrip.select(index);

                    break;
            }
        }

        $('.addaddress').live('click', function () {
            $.ajax({
                url: '@Url.Content("~/Entity/CreateAddress")',
                type: "GET",
                cache: false,
                error: function (error) {
                    window.location.href = '@Url.Content("~/Error/Index")';
                },
                success: function (data) {
                    isSessionExpired(data, '@Url.Content("~/Account/Login")');

                    $('#dvCreateNew').remove();
                    $('<div />', { id: 'dvCreateNew' }).appendTo('body');
                    $('#dvCreateNew').empty().html(data);
                    $('#dvCreateNew').dialog({
                        title: 'Add New Address',
                        width: 900,
                        height: 'auto',
                        modal: true
                    });
                }
            });
        });
    });
    function bindChangeEvent() {

        $('input[type=text],textarea,input[type=password],input:password').change(function () {
            console.log("Change Trigger for " + this.id);
            setformChanged(true);
        });
        setformChanged(false);
    }
    function setformChanged(changed) {
        if (changed == null)
            changed = true;
        formValuesChanged = changed;
        if (changed)
            alertBeforeRedirect();
        else
            stopAlertBeforeRedirect();
        console.log("form values changed [" + changed + "]");
    }
    function onSelect(e) {

        var test = $('.k-content.k-state-active')[0];
        if (test) {
            var currentTabId = test.id.replace("tabstrip-", "");
            if (formValuesChanged) {

                doConfirm('Are you sure want to navigate from this tab , all unsaved data will be lost?',
                    function yes() {
                        updateTab($(e.item).attr("type"), $(e.contentElement));
                        setformChanged(false);

                        $('form').each(function () {
                            this.reset();
                        });
                    }, function no() {
                        var tabstrip = $("#tabstrip").kendoTabStrip().data("kendoTabStrip");
                        tabstrip.select(currentTabId - 1);
                    });
            }
            else
                updateTab($(e.item).attr("type"), $(e.contentElement));
        }
        else
            updateTab($(e.item).attr("type"), $(e.contentElement));

    }
    function updateTab(typ, contentElement) {

        if (typ == null)
            return;

        $("#dvloader").hide();

        var updateBtn = $('#btnUpdate');
        updateBtn.unbind();
        updateBtn.show();
        var appendHtml = "";

        switch (typ) {
            case 'UserProfile':
                updateBtn.click(updateProfile);
                break;
            case 'System':
                updateBtn.click(updateSystemSettings);
                break;
            case 'Enittes':
                updateBtn.click(updateEntitySetting);
                break;
            case 'Sharepoint':
                updateBtn.click(updateSharepointSettings);
                break;
            case 'Logs':
                updateBtn.unbind();
                updateBtn.hide();
                break;
            case 'DefaultDocuments':
                updateBtn.unbind();
                updateBtn.hide();
                break;
            case 'ReportsTemplates':
                updateBtn.unbind();
                updateBtn.hide();
                break;
            case 'ReportServer':
                updateBtn.unbind();
                updateBtn.hide();
                updateBtn.click(updateReportServerSettings);
            case 'Groups':
                updateBtn.unbind();
                updateBtn.hide();
                break;
            case 'Roles':
                updateBtn.unbind();
                updateBtn.hide();
                break;

        }

        //if ($.inArray(typ, loadedTabs) != -1)
        //    return;

        loadedTabs.push(typ);
        contentElement.empty().html("Loading ... <img src='@Url.Content("~/Images/loader.gif")' />");

        $.ajax({
            url: '@Url.Content("~/Setting/GetSettings")',
            data: { settingHead: typ },
            type: "GET",
            cache: false,
            error: function (error) {

                window.location.href = '@Url.Content("~/Error/Index")';
            },
            success: function (data) {
                isSessionExpired(data, '@Url.Content("~/Account/Login")');
                if (typ == 'Enittes') {
                    contentElement.empty().html("<h2>Address <img src='@Url.Content("~/Images/add.png")' class='add addaddress' title='Click to add new address' /></h2><div id='dvAddress'>" + data + "</div>");
                }
                else {
                    contentElement.empty().html(appendHtml + data);
                }
                //$(e.contentElement).css("height","10px" )
                $.validator.unobtrusive.parse(contentElement);

            }
        });
        return;
    }

    function updateProfile() {
        //following function implemented in _UserProfile
        InvokeProfileUpdate();
    }
    function updateSystemSettings() {

        //following function implemented in _SystemSettings
        InvokeSystemSettingUpdate();
    }
    function updateSharepointSettings() {

        //following function implemented in _SystemSettings
        InvokeSharepointSettingUpdate();
    }
    function updateEntitySetting() {
        $("#updateMessage").empty().html("Updating entity settings");
        $("#dvloader").show();
        $("#btnUpdate").hide();
        $.ajax({
            url: '@Url.Content("~/User/UpdateEntityAddress")',
            type: "POST",
            cache: false,
            error: function (error) {
                window.location.href = '@Url.Content("~/Error/Index")';
            },
            success: function (data) {
                isSessionExpired(data, '@Url.Content("~/Account/Login")');
                if (data.success) {
                    doAlert('Address information saved successfully');
                }
                $("#updateMessage").empty();
                $("#dvloader").hide();
                $("#btnUpdate").show();
            }
        });

    }
    function loadAddress() {
        $.ajax({
            url: '@Url.Content("~/Entity/GetAddress")',
            type: "GET",
            cache: false,
            error: function (error) {
                window.location.href = '@Url.Content("~/Error/Index")';
            },
            success: function (data) {
                $('#dvAddress').html(data);
            }
        });
    }
    function GetTabIndex(type, childArray) {
        var index = -1;
        jQuery.each(childArray, function (i, val) {
            if ($(val).attr("type") == type) {
                index = i;
                return false;
            }
        });
        return index;
    }

    function updateReportServerSettings() {

    }
</script>

SMSF/Presentation/SMSF.Web/Views/Setting/_CreateGroup.cshtml
@model DBASystem.SMSF.Contracts.ViewModels.UserGroupModel

@using (Ajax.BeginForm("CreateGroup", new { }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "onBegin", OnSuccess = "onSuccess", OnFailure = "onFailure" }, new { id = "frmCreateGroup" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.Status)

    <table style="width: 100%" class="nobordertable">
        <tr>
            <td style="width: 20%">
                Name
            </td>
            <td>
                @Html.TextBoxFor(model => model.Title, new { placeholder = "Group Name" })
                @Html.ValidationMessageFor(model => model.Title)
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td>
                @Html.TextAreaFor(model => model.Description, new { style = "width: 300px; height: 60px", placeholder = "Enter group description here" })
                @Html.ValidationMessageFor(model => model.Description)
            </td>
        </tr>
        <tr>
            <td></td>
            <td id="tdButtons">
                <input type="submit" value="@if (Model.ID != 0){<text>Update</text>}else{<text>Save</text>}" />
                <input type="button" value="Cancel" id="btnCancel" />
                <img src='@Url.Content("~/Images/loader.gif")' style="display: none" />
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(function () {
        $.validator.unobtrusive.parse("#frmCreateGroup");

        $('#dvCreateNew #btnCancel').unbind('click').click(function () {
            $('#dvCreateNew').dialog('close');
        });
    });

    function onBegin() {
        if ($('#frmCreateGroup').valid()) {
            $('#dvCreateNew #tdButtons input').hide();
            $('#dvCreateNew #tdButtons img').show();
            return true;
        }

        return false;
    }

    function onFailure(context) {
        window.location.href = '@Url.Content("~/Error/Index")';
    }

    function onSuccess(context) {
        if (context = "success") {
            loadGroup();
            $('#dvCreateNew').dialog('close');
            if ('@Model.ID' == 0)
                setStatusBarMessage('New user group added');
            else
                setStatusBarMessage('User group updated');
        }
    }
</script>

SMSF/Presentation/SMSF.Web/Views/Setting/_CreateRole.cshtml
@model DBASystem.SMSF.Contracts.ViewModels.RoleModel

@using (Ajax.BeginForm("CreateRole", new { }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnBegin = "onBegin", OnSuccess = "onSuccess", OnFailure = "onFailure" }, new { id = "frmCreateRole" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.Status)

    <table style="width: 100%" class="nobordertable">
        <tr>
            <td style="width: 20%">
                Name
            </td>
            <td>
                @Html.TextBoxFor(model => model.Title, new { placeholder = "Role Name" })
                @Html.ValidationMessageFor(model => model.Title)
            </td>
        </tr>
        <tr>
            <td>Description</td>
            <td>
                @Html.TextAreaFor(model => model.Description, new { style = "width: 300px; height: 60px", placeholder = "Enter role description here" })
                @Html.ValidationMessageFor(model => model.Description)
            </td>
        </tr>
        <tr>
            <td></td>
            <td id="tdButtons">
                <input type="submit" value="@if (Model.ID != 0){<text>Update</text>}else{<text>Save</text>}" />
                <input type="button" value="Cancel" id="btnCancel" />
                <img src='@Url.Content("~/Images/loader.gif")' style="display: none" />
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(function () {
        $.validator.unobtrusive.parse("#frmCreateRole");

        $('#dvCreateNew #btnCancel').unbind('click').click(function () {
            $('#dvCreateNew').dialog('close');
        });
    });

    function onBegin() {
        if ($('#frmCreateRole').valid()) {
            $('#dvCreateNew #tdButtons input').hide();
            $('#dvCreateNew #tdButtons img').show();
            return true;
        }

        return false;
    }

    function onFailure(context) {
        window.location.href = '@Url.Content("~/Error/Index")';
    }

    function onSuccess(context) {
        
        if (context = "success") {
            loadRoles();
            $('#dvCreateNew').dialog('close');
            if ('@Model.ID' == 0)
                setStatusBarMessage('New role added');
            else
                setStatusBarMessage('Role updated');
        }
    }
</script>

SMSF/Presentation/SMSF.Web/Views/Setting/_SharepointSetting.cshtml
@model DBASystem.SMSF.Contracts.ViewModels.SharePointSettingModel

@using (Html.BeginForm("UpdateSharePointSetting", "Setting", FormMethod.Post, new { id = "frmSharepointSetting" }))
{
   
    <div class="SharePointTabContainer" style="overflow:auto">

        <table class="nobordertable" style="width:100%">
            <tr>
                <td colspan="2"><h2>Sharepoint Settings</h2><a id="Sharepoint_Anchor" name="One" /></td>
            </tr>
            <tr>
                <td style="vertical-align:top; width:20%">URL</td>
                <td style="width: 80%">
                    @Html.TextBoxFor(model => model.SharePointUrl, new { @class = "Sharepoint" })
                    @Html.ValidationMessageFor(model => model.SharePointUrl)
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">User Name</td>
                <td>
                    @Html.TextBoxFor(model => model.UserName, new { @class = "Sharepoint" })
                    @Html.ValidationMessageFor(model => model.UserName)
                    <div>
                        Set Password
                        @Html.CheckBox("SetPassword", false)
                    </div>
                </td>
            </tr>

            <tr class="sharepointPassword ignore" style="display:none">
                <td style="vertical-align:top;">Password</td>
                <td>
                    @Html.PasswordFor(model => model.Password, new { @class = "Sharepoint" })
                    @Html.ValidationMessageFor(model => model.Password)
                </td>
            </tr>
            <tr class="sharepointPassword" style="display:none">
                <td style="vertical-align:top;">Confrm Passowrd</td>
                <td>
                    @Html.PasswordFor(model => model.ConfirmPassword)
                    @Html.ValidationMessageFor(model => model.ConfirmPassword)
                </td>
            </tr>

            <tr>
                <td style="vertical-align:top;">Max File Size</td>
                <td>
                    @Html.TextBoxFor(model => model.MaximumFileSize, new { @class = "Sharepoint", maxlength = "3", style = "width:40px" })<span id="dvHelp"> MB</span>

                    @Html.ValidationMessageFor(model => model.MaximumFileSize)
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">Allowed File Types</td>
                <td>
                    @Html.TextBoxFor(model => model.AllowedFileTypes, new { @class = "Sharepoint" })<span id="dvHelp"> comma sepreted values</span>

                    @Html.ValidationMessageFor(model => model.AllowedFileTypes)
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">Job Default Documents Path</td>
                <td>
                    @Html.TextBoxFor(model => model.JobDefaultDocumentsPath, new { @class = "Sharepoint" })

                    @Html.ValidationMessageFor(model => model.JobDefaultDocumentsPath)
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">Template Reports Path</td>
                <td>
                    @Html.TextBoxFor(model => model.ReportTemplatePath, new { @class = "Sharepoint" })

                    @Html.ValidationMessageFor(model => model.ReportTemplatePath)
                </td>
            </tr>
        </table>
    </div>
}

<script>

    //$(".SharePointTabContainer").niceScroll({ cursorborder: "", cursorcolor: "#80bedd", boxzoom: false });
    $(function () {
        var height = $(document).height() - 250;
        $(".SharePointTabContainer").height(height);
                
        $.validator.setDefaults({ ignore: ".ignore" });
        var settngs = $.data($('form')[0], 'validator').settings;
        settngs.ignore = ".sharepointPassword";

        $("#SetPassword").change(function() {
            if ($(this).is(":checked")) {
                $(".sharepointPassword").show();
            } else {
                $(".sharepointPassword").hide();
            }
        });
        bindChangeEvent();
        setformChanged(false);
    });
    function InvokeSharepointSettingUpdate() {

        $.validator.unobtrusive.parse($('#frmSharepointSetting'));
        if (!$("#frmSharepointSetting").valid())
            return false;

        $('#imgSystemSettingLoader').show();
        $('#btnSaveSettings').hide();

        var $form = $("#frmSharepointSetting");
        $("#updateMessage").empty().html("Updating Sharepoint Settings");
        $("#dvloader").show();
        $("#btnUpdate").hide();

        $.ajax({
            type: "POST",
            url: $form.attr('action'),
            data: $form.serialize(),
            error: function (xhr, status, error) {
                $("#updateMessage").empty();
                $("#dvloader").hide();
                $("#btnUpdate").show();
                doAlert("There was an while updating system settings please try again later");
            },
            success: function (data) {
                SettingSaved(data);
            }
        });
    }
    function SettingSaved(data) {
        $("#updateMessage").empty();
        $("#dvloader").hide();
        $("#btnUpdate").show();
        if (data.success) {
            isSessionExpired(data, '@Url.Content("~/Account/Login")');
            $('#imgSystemSettingLoader').hide();
            $('#btnSaveSettings').show();

            if (data.success) {
                var alertMessage = "Sharepoint settings saved successfully.";
                $(".sharepointPassword").hide();
                $('#SetPassword').prop('checked', false);
                doAlert(alertMessage);
                setformChanged(false);
            }
        }
        else
            doAlert("There was an error while updating system settings please try again later");
    }


</script>